### ISSUE TITLE
Using H3_DATAGRAM_ERROR is weird

### ISSUE THREAD

**Issue by LPardue** [DavidSchinazi/draft-schinazi-httpbis-wrap-up#3]
> Endpoints that abort the request stream due to an unexpected or malformed WRAP_UP capsule received over HTTP/3 SHOULD use the H3_DATAGRAM_ERROR error code when aborting the stream.

I realize we defined that error code but it especially sticks out if we consider WRAP_UP could be used for a capsule protocol stream that doesn't even use datagrams. Ok ok, https://www.rfc-editor.org/rfc/rfc9297#section-5.2 says 

> Description: Datagram or Capsule Protocol parse error

But I can see people getting quite confused by this name, if for example we had a [connect-tcp stream](https://httpwg.org/http-extensions/draft-ietf-httpbis-connect-tcp.html#name-use-of-the-capsule-protocol) that observed two WRAP_UPS and wanted to reset

I think the answer is probably to define generic [H2_|H3]_CAPSULE_ERROR in https://LPardue.github.io/draft-pardue-capsule-ext-guidance/draft-pardue-capsule-ext-guidance.html. So jsut using this issue to highlight something that sticks out that might get addressed elsewhere.

**Comment by DavidSchinazi** [comment]
Yeah it's kinda. I'll update WRAP_UP to match what we did for [connect-ip](https://www.rfc-editor.org/rfc/rfc9484#section-4.7.2-8):

> If any of the capsule fields are malformed upon reception, the receiver of the capsule MUST follow the error-handling procedure defined in [Section 3.3](https://rfc-editor.org/rfc/rfc9297#section-3.3) of [[HTTP-DGRAM](https://www.rfc-editor.org/rfc/rfc9484#RFC9297)].

Totally agree that we should fix this in draft-pardue-capsule-ext-guidance. I filed https://github.com/LPardue/draft-pardue-capsule-ext-guidance/issues/1
